version: "3.1"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uw_docker_container
    ports:
      - 80:80
    volumes:
      - C:\uw_docker:/app
    networks:
      - uw_docker_arangodb_network

  arangodb:
    image: arangodb:3.11.3
    container_name: uw_docker_arango_3.11.3_container
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - C:\uw_docker\arangodb:/var/lib/arangodb3
    networks:
      - uw_docker_arangodb_network

networks:
  uw_docker_arangodb_network: